import os
from typing import List
from pydantic import AnyHttpUrl, BeforeValidator
from pydantic_settings import BaseSettings, SettingsConfigDict
from typing_extensions import Annotated

def parse_cors_origins(v: str | List[str]) -> List[str]:
    if isinstance(v, str) and not v.startswith("["):
        return [i.strip() for i in v.split(",")]
    elif isinstance(v, (list, str)):
        return v
    raise ValueError(v)

class Settings(BaseSettings):
    PROJECT_NAME: str = "Traffic AI Backend API"
    API_V1_STR: str = "/api/v1"
    
    # SQLite fallback local DB URL
    DATABASE_URL: str = "sqlite+aiosqlite:///./traffic_system.db"
    
    # Path to serve the images/PDFs generated by the CV pipeline
    MEDIA_DIR: str = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "..", "..", "core-cv-pipeline", "challans_output")
    )
    
    BACKEND_CORS_ORIGINS: Annotated[
        List[str], BeforeValidator(parse_cors_origins)
    ] = ["*"]

    model_config = SettingsConfigDict(
        case_sensitive=True,
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore"
    )

settings = Settings()
